apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testapp
spec:
  metrics:
    - name: testapp
      provider:
        opsmx:
          gateUrl: https://argoqa.isd-dev.opsmx.net/
          user: admin
          application: argocd-qa01-10171
          baselineStartTime: "2022-08-20T13:15:00Z"
          lifetimeHours: "0.1"
          threshold: 
            pass: 80
            marginal: 60
          services:
          - logTemplateName: testLogTemplateName67248
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: "baseapp-rest-1"
            canaryLogScope: "canaryapp-rest-1"
            metricTemplateName: datadogcustom
            metricScopeVariables: "variable1"
            baselineMetricScope: "service:baseapp"
            canaryMetricScope: "service:canaryapp"
